### ISSUE TITLE
Feedback Sprint 2

### ISSUE THREAD

**Issue by MarciaMillanao** [nahytar/scl-2018-05-bc-core-am-datadashboard#1]
Hola chicas!
Estuve revisando el avance que llevan y tengo algunos comentarios:

1.- Utilicen milestones para ver el avance de los issues, esto es como un trello pero en github (similar) , les dejo dos vídeos de guía [https://www.youtube.com/watch?v=9SZSHGA95x4](url)
[https://www.youtube.com/watch?v=nI5VdsVl0FM](url)

2.- Usen los issues para coordinarnse y comunicarse entre ustedes.

3.- Utilicen comentarios a lo largo de su proyecto en los archivos.

4.- Como tienen varios archivos CSS, les recomiendo crear una carpeta y dejarlos todos guardado dentro, para así se vea un proyecto más ordenado.

Vamos con todo.!

**Comment by nahytar** [comment]
Gracias Marcia.
